### PR TITLE
Update builds for Python 3.11

### LINKED ISSUE #700: Support for Python 3.11
## 🚀 Feature

I know it is eaarly (Python 3.11 has just been released yesterday) but we are hoping in Apache Airflow to a much faster cycle of adding new Python releases - especially that Pyhon 3.11 introduces huge performance improvements (25% is the average number claimed) due to a very focused effort to increase single-threaded Python performance (Specialized interpreter being the core of it but also many other improvements) without actually changing any of the Python code.

### Motivation

The papermill is one of the dependencies of Airlfow that need to support newer Python version so this issue is here to make you aware that we are eaager (also to help if needed) to make it faster, possibly by talking to dependencies of Beam as well (who are oftten also direct dependencies of Airflow) and help them as well. I perfectly understand we need to bubble up support so that your dependencies support them first.

Nice summary of Py3.11 support is here: https://pyreadiness.org/3.11/ - it's not very green obviously, but I hope it gets greener soon.

I'd appreciate if someone in the ntarct team attempted to migrate and have a PR running (and failing possibly until all prerequisite are met so that we can also track the progress and possibly help each other to solve any problems. I know PyArrow is blocking for now, but this is going to be solved soon lilely with https://github.com/apache/arrow/pull/14499 and just opening a failing PR with it might be a good start.

I just opened such PR in Apache Airflow yesterday and plan to keep it open until it gets green :)

https://github.com/apache/airflow/pull/27264

I think it would be fantastic if we could as the open source community migrate to the new Python much faster.

Looking forward to cooperation on that one :)

### PR DESCRIPTION
**Pull request by tirkarthi**
## What does this PR do?

Add Python 3.11 to CI

Fixes #700

### CODE REVIEW

**Comment by kurtqq** [comment]
@MSeal can you please review? lack of Python3.11 support is becoming an issue

**Comment by kurtqq** [comment]
hi @willingc can you help with review?

**Comment by kurtqq** [comment]
@bryanchen-d  is someone from nteract ownes this repo? :(

**Comment by bryanchen-d** [comment]
> @bryanchen-d is someone from nteract ownes this repo? :(
I haven't touched this area before, from the history of the ci.yml, looks like @willingc would be the best person to take a look.

**Comment by kurtqq** [comment]
OK I guess this repo is not maintained and it's time to start looking for alternatives

**Comment by MSeal** [comment]
Apologies @kurtqq -- health issues and startup land have eaten a lot of my time. I'm going to be putting more weekend time getting papermill caught up on issues / maintenance.

**Review by MSeal — APPROVED** [review]

**Comment by kurtqq** [comment]
> Apologies @kurtqq -- health issues and startup land have eaten a lot of my time. I'm going to be putting more weekend time getting papermill caught up on issues / maintenance.

thank you. waiting for it.

**Comment by kurtqq** [comment]
@MSeal checking in on this. is there estimated time to resolve and release with 3.11 support?

**Comment by kurtqq** [comment]
Thank you @tirkarthi I eventually decided to drop this project for another alternative. can't trust on this kept alive.

**Review by willingc — APPROVED** [review]

**Comment by noahlove** [comment]
> Thank you @MSeal I eventually decided to drop this project for another alternative. can't trust on this kept alive.

@kurtqq , curious what project did you end up choosing as a replacement

**Comment by MSeal** [comment]
Fixing builds and adding 3.12 in second PR using this branch as a base.

**Pull request closed without merging**
