### PR TITLE
Fix CI

### LINKED ISSUE #663: Broken CI
## 🐛 Bug
By #658, the format error is occurring in flake8.

And Python 3.8 ~ 3.10 jobs are also failing, so investigate as much as possible.

### PR DESCRIPTION
**Pull request by reoono**
## What does this PR do?

CI jobs are failing, fix it.

At first, we will fix it starting with a simple formatting error.

Fixes #663

### CODE REVIEW

**Comment by reoono** [comment]
In 3.8 ~ 3.10, `TestBrokenNotebook2` fails.

Comparing the results of `papermill_io.read(notebook_path)` with 3.7, the test fails because `stderr` is being output to `outputs`.

```
{
 "cells": [
  {
    ...
  },
  {
    ...
  },
  {
    ...
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "a29dda52",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2022-05-18T19:18:57.491381Z",
     "iopub.status.busy": "2022-05-18T19:18:57.491027Z",
     "iopub.status.idle": "2022-05-18T19:18:57.764096Z",
     "shell.execute_reply": "2022-05-18T19:18:57.763670Z"
    },
    "papermill": {
     "duration": 0.284906,
     "end_time": "2022-05-18T19:18:57.764818",
     "exception": true,
     "start_time": "2022-05-18T19:18:57.479912",
     "status": "failed"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/tmp/ipykernel_127658/3114338127.py:2: DeprecationWarning: Importing display from IPython.core.display is deprecated since IPython 7.14, please import from IPython display\n",
      "  from IPython.core.display import display, HTML\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<style>.container { width:100% !important; }</style>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "ename": "AssertionError",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mAssertionError\u001b[0m                            Traceback (most recent call last)",
      "Input \u001b[0;32mIn [2]\u001b[0m, in \u001b[0;36m<cell line: 5>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      2\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mIPython\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mcore\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mdisplay\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m display, HTML\n\u001b[1;32m      3\u001b[0m display(HTML(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m<style>.container \u001b[39m\u001b[38;5;124m{\u001b[39m\u001b[38;5;124m width:100\u001b[39m\u001b[38;5;124m%\u001b[39m\u001b[38;5;124m !important; }</style>\u001b[39m\u001b[38;5;124m\"\u001b[39m))\n\u001b[0;32m----> 5\u001b[0m \u001b[38;5;28;01massert\u001b[39;00m \u001b[38;5;28;01mFalse\u001b[39;00m\n",
      "\u001b[0;31mAssertionError\u001b[0m: "
     ]
    }
   ],
   "source": [
    "# This causes multiple output elements to be created, one of type \"display_data\" and another of type \"error.\"\n",
    "from IPython.core.display import display, HTML\n",
    "display(HTML(\"<style>.container { width:100% !important; }</style>\"))\n",
    "\n",
    "assert False"
   ]
  },
  {
    ...
  }
 ],
 "metadata": {
     ...
  },
  "papermill": {
      ...
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
```

**Comment by reoono** [comment]
After changing to the recommended method as follows, I no longer get multiple outputs.
Therefore, I have suppressed DeprecatedWarnings on import.

```
from IPython import display
display.HTML("<style>.container { width:100% !important; }</style>")
```

**Comment by reoono** [comment]
@MSeal 
The work has been completed, please check when you are available.
Thank you for your cooperation.

**Review by MSeal — APPROVED** [review]
TY!

**Pull request merged**
