### PR TITLE
Hiding Ingested Parameters if `--report-mode`

### PR DESCRIPTION
**Pull request by LeonardAukea**
Added functionality to hide ingested parameters in output notebook if executed with `--report-mode`

I don't think it makes sense to show the ingested parameters in the output notebook when using `--report-mode`.  Here is the issue I created. #253

### CODE REVIEW

**Comment by MSeal** [comment]
Thanks for the fix. You have a trivial whitespace issue making flake8 complain. I can merge once you clean that line up.

**Comment by LeonardAukea** [comment]
@MSeal Whitespace is removed.

**Comment by MSeal** [comment]
Thanks for the fix!

**Comment by wrathagom** [comment]
I think this PR may have introduced a small error as reported on #282

**Pull request merged**
