### PR TITLE
Use Black to format Python parameters for versions >= 3.6

### LINKED ISSUE #436: PrettyPrint parameters
When we inject parameters they form very large single lines if the parameter is a map or list of arguments. It's be nice for readability if the parameter injection was smart about formatting inputs and ran them through a linter or printed maps / lists in a way that was more legible. This might become language / kernel specific, but would still be a solid improvement to generated notebooks.

### PR DESCRIPTION
**Pull request by petebachant**
Resolves #436.

I picked cutoff values for when to use newlines/indents based on my own practices. Was thinking of trying to limit line length, but we don't know the variable name so we can't calculate the full line length.

### CODE REVIEW

**Comment by MSeal** [comment]
IMO I think importing and reusing https://github.com/psf/black/blob/master/black.py would do better here. Choosing split by element count will still look ugly with nested objects that are really long, or one long string.

Also for testing, we'll probably need to either run the test results through the same formatter function, or pass a flag to not format for most tests and separately test for just the format impact.

**Comment by petebachant** [comment]
@MSeal the tests are actually all passing even when run through the Black formatter.

**Comment by MSeal** [comment]
I'll try to test this out tonight. Thanks for getting the PR up!

**Comment by MSeal** [comment]
Work great, merging for the next major release :)

**Pull request merged**
