### PR TITLE
Added isolated depedency installation options

### PR DESCRIPTION
**Pull request by MSeal**
Implements https://github.com/nteract/papermill/issues/257

My only worry with merging this is around existing users who have `papermill` as a dependency setup assuming s3 or azure bindings are available. This might mean we should wait for 1.0 release? Gcs users did want their dependencies isolated from standard installations before releasing that plugin though.

### CODE REVIEW

**Comment by betatim** [comment]
Who are Gcs users?

**Comment by betatim** [comment]
I'd keep S3 and Azure bundled/installed by default for two (?) releases to give people a chance to update their dependencies.

Ideal would be to emit a `DeprecationWarning` to let people know the change is coming but I am not quite sure if we can detect if they explicitly used `pip install papermill[s3]` or just `pip install papermill`.

**Comment by betatim** [comment]
In the last release IO and execution engine "plugins" were enabled by using entrypoints: https://github.com/nteract/papermill/issues/266. I think that is a good way of allowing people to extend papermill. 

Not sure I understand what you mean with "I'd need to create a new setup.py, etc. which I think is a bit heavier-weight and might affect adoption of building custom extensions". I think if you want `pip install my-awesome-engine` to work you need a `setup.py`. Maybe we should provide a template for the `setup.py` as part of the docs in #266 to make it easier for those not familliar with Python packaging to do the right thing.

**Comment by betatim** [comment]
To make travis happy we need to install the Azure related packages in the test environment. I think that is better than removing the tests.

**Comment by mckev-amazon** [comment]
Good point - after reading the document I referenced, I realize that the burden is on the plugin developer only to configure setup.py.  In my hastiness I incorrectly assumed that this was an end-user responsibility - indeed it's not.  In that regard, providing documentation to the plugin developer is certainly reasonable.  As you suggest, a setup.py template would be helpful.

I suppose based on that I'm still not entirely clear on, if we had to pick one approach, which is the most suitable.  I couldn't find anything that suggests that one is more canonical over the other.  If we want to optimize for adoption of new engine implementations, the first two approaches on the surface could be considered more approachable, on the other hand, entrypoints is more explicit and provides more flexibility as it allows one package to expose multiple entrypoints. 

All that said, as I'm typing this I'm realizing I'm probably splitting hairs at this point :-)

**Pull request merged**
