### PR TITLE
Changed yaml parsing to preserve types in notebook. Made multiple yaml inputs valid.

### PR DESCRIPTION
**Pull request by MSeal**
Yaml inputs had to be composed before calling papermill when there didn't seem to be a strict reason to limit inputs. This change makes it so you can mix and match the command inputs to fit your incoming parameter data. In my case I had multiple json objects as well as individual parameters being collected that needed separate assignments in the notebook. Now later yamls will override earlier ones with individual parameters taking highest preference.

Furthermore, passing a json object will give you a dict in your notebook instead of a string. This makes passing complex parameters very nice for consumption in the notebook.

Also added specs for R parameter decoding (and validated they worked even though there aren't R kernel automated specs yet in the repo).

### CODE REVIEW

**Comment by MSeal** [comment]
The R calls corresponding to the R decode specs:

```
#R version 3.3.2 

library("rjson")

t0 = "foo"
t1 = "{\"foo\": \"bar\"}"
t2 <- fromJSON(t1)

print(t0)
print(t1)
print(t2)

t3 = list("foo" = "bar")
t4 = list("foo" = "\"bar\"")

print(t3)
print(t4)

t5 = list("foo" = list("bar"))
t6 = list("foo" = list("bar" = "baz"))
t7 = list("foo" = list("bar" = "\"baz\""))

print(t5)
print(t6)
print(t7)

t8 = list("foo")
t9 = list("foo", "\"bar\"")

print(t8)
print(t9)

t10 = list(list("foo" = "bar"))
t11 = list(list("foo" = "\"bar\""))

print(t10)
print(t11)

t12 = 12345
t13 = -54321

print(t12)
print(t13)

t14 = TRUE
t15 = FALSE

print(t14)
print(t15)
```

with outputs:

```
[1] "foo"
[1] "{\"foo\": \"bar\"}"
$foo
[1] "bar"

$foo
[1] "bar"

$foo
[1] "\"bar\""

$foo
$foo[[1]]
[1] "bar"


$foo
$foo$bar
[1] "baz"


$foo
$foo$bar
[1] "\"baz\""


[[1]]
[1] "foo"

[[1]]
[1] "foo"

[[2]]
[1] "\"bar\""

[[1]]
[[1]]$foo
[1] "bar"


[[1]]
[[1]]$foo
[1] "\"bar\""


[1] 12345
[1] -54321
[1] TRUE
[1] FALSE
```

**Comment by willingc** [comment]
@MSeal cool! Can you split this PR into two: one for CLI/multiple and one for R stuff? Will be easier to test, review, and merge. Thanks.

**Comment by MSeal** [comment]
Sure I'll pull the R specs into another PR tonight

**Comment by MSeal** [comment]
Closing this PR for the 3 broken down versions.

**Pull request closed without merging**
