### PR TITLE
 Using logger instead of print statement

### PR DESCRIPTION
**Pull request by schrockn**
Currently execute_notebook is hard-coded to print its two messages
to stderr using print. This PR changes this to use the python
logging framework.

First PR so let me know if you want this at all or in a totally different way. Thanks!

P.S. This project is so cool. Thank you for open sourcing it.

### CODE REVIEW

**Comment by MSeal** [comment]
Hi @schrockn ! Thanks for opening the PR (and for the project praise).

I do agree we should control logging here, but I think we can capture it a little better than we do today. Instead of setting a `printer` method I think we should pass a [logger object](https://docs.python.org/3/library/logging.html) which defaults to something like [this post](https://stackoverflow.com/questions/14058453/making-python-loggers-output-all-messages-to-stdout-in-addition-to-log) except with stderr as the output channel. This way we conform to a more known interface and allow users to alter the logging pattern with known conventions easier.

**Comment by schrockn** [comment]
@MSeal do you want this to default to just the root logger? Or do you want a named logger with the `papermill` namespace?

```
import logging
logging.info('message')
```
or

```
import logging
logger = logging.getLogger('papermill')
logger.info('message')
```

**Comment by MSeal** [comment]
Actually, @betatim pointed out to me that we should instead just reference the logger rather than pass it around. We could let the execute function either pass the log level (which we could expose to the CLI layer easily) or external code could load the named logger.

**Comment by schrockn** [comment]
Updated per-request. Python logging framework is awkward to test without library support so I have removed the test testing the actual messages..(LogCapture in https://github.com/Simplistix/testfixtures/ is promising but adding that as a dependency is it's own discussion)

**Pull request merged**
