### PR TITLE
Add Python 3.7 to travis tests

### PR DESCRIPTION
**Pull request by willingc**

### CODE REVIEW

**Comment by tacaswell** [comment]
Experimentally you need `sudo` to get the 3.7 tests to work (see https://github.com/matplotlib/matplotlib/blob/6001bf2a1d9058f042323b0d32d0f29ca2669c81/.travis.yml#L81-L82)

**Comment by willingc** [comment]
Thanks @tacaswell. Great to see you even if it was brief.

**Comment by cclauss** [comment]
Experimentally you need both sudo and xenial get the 3.7 tests to work on Travis (see #188)

**Comment by MSeal** [comment]
@willingc closing this as @cclauss added the 3.7 allowed_failure until google cloud update's its libraries used in boto to 3.7

**Pull request closed without merging**
