### PR TITLE
Remove use of ansiwrap

### PR DESCRIPTION
**Pull request by soggyomelette**
## What does this PR do?

Removes use of ansiwrap in the package for the reasons in #680

### CODE REVIEW

**Review by MSeal — APPROVED** [review]
Thanks for identifying and opening the PR for changes!

**Comment by dhirschfeld** [comment]
It would be great to get this fix in a release as, now that Python 3.12 is released, this is causing issues for any packages depending on `papermill`.

**Comment by MSeal** [comment]
Got it, alright I can prepare a release of papermill to account for recent python changes. There's been a backlog of issues / PRs that will need to be a put into a fixed release build.

**Comment by dhirschfeld** [comment]
On the `conda-forge` front, we've patched the repodata so there's no longer breakage, but instead you  won't be able to install `papermill` in a 3.12 environment... at least until the new version is published.

**Comment by MSeal** [comment]
Working through some other packaging issues, but will have a 3.12 build out once those are solved

**Comment by MSeal** [comment]
@dhirschfeld 2.5.0 is released to PyPI now

**Pull request merged**
