### PR TITLE
add cli tests for click

### PR DESCRIPTION
**Pull request by willingc**
- try testing using click's test cli runner

### CODE REVIEW

**Comment by rgbkrk** [comment]
Awesome! I'm so glad to see tests getting instrumented for the CLI, thank you @willingc! Is this still WIP? I see the Travis Greenlight so I thought I'd ask.

**Comment by MSeal** [comment]
I coincidentally also [made CLI tests](https://github.com/nteract/papermill/pull/88) today before looking here. Looks like these actually go into calling execute though which is great!

**Comment by willingc** [comment]
@rgbkrk @MSeal These are still a work in process. A fully functioning notebook would be helpful for testing. 

@MSeal More tests are better than not enough ;-)

**Comment by willingc** [comment]
Removing the WIP. Click was giving a bunch of warnings about using the future import so I removed and made the emojis explicit u" ".

**Comment by rgbkrk** [comment]
It looks like a rebase is necessary for this one, otherwise we should go ahead and bring in the enhanced test coverage here.

**Comment by willingc** [comment]
@rgbkrk Rebased :-)

**Pull request merged**
