### PR TITLE
fix: avoid collisions with parameters and user namespace

### PR DESCRIPTION
**Pull request by adparker**
* added a super simple test
* switched from kwargs to parameters to avoid a conflict between notebook parameters and user namespace

### CODE REVIEW

**Comment by rgbkrk** [comment]
Sweet! How should this get invoked for Travis?

**Comment by rgbkrk** [comment]
You can add the testing line in the `script` section for Travis to run the test: https://github.com/nteract/papermill/blob/997bbda3c24ee4b9863344645cc5e093cd77ddb6/.travis.yml#L8

**Comment by rgbkrk** [comment]
You'll also want to `pip install pytest` in the install, so the travis yaml will look like:

```yaml
language: python
python:
  - "2.7"
  - "3.5"
# command to install dependencies
install:
  - pip install pytest
  - pip install -e .
# command to run tests
script: py.test
```

**Comment by rgbkrk** [comment]
After this we'll certainly put out a patch release since this wasn't fully working yet. :wink:

**Comment by rgbkrk** [comment]
Ok -- issue we run into here -- the notebook is python2 and nbconvert won't fallback to python3.

**Comment by adparker** [comment]
Very hacky to get this to work in both Python 3 and Python 2. Sad.

**Comment by adparker** [comment]
PTAL: @rgbkrk and @ewmassey

**Comment by rgbkrk** [comment]
Cool, I'll go ahead and bring this in.

**Comment by rgbkrk** [comment]
Thanks @adparker!

**Pull request merged**
